export const REGISTER_EMPLOYER = "REGISTER_EMPLOYER";
export const REGISTER_EMPLOYER_SUCCESS = "REGISTER_EMPLOYER_SUCCESS";
export const REGISTER_EMPLOYER_FAIL = "REGISTER_EMPLOYER_FAIL";

export const REGISTER_EMPLOYEE = "REGISTER_EMPLOYEE";
export const REGISTER_EMPLOYEE_SUCCESS = "REGISTER_EMPLOYEE_SUCCESS";
export const REGISTER_EMPLOYEE_FAIL = "REGISTER_EMPLOYEE_FAIL";

export const LOGIN_EMPLOYER = "LOGIN_EMPLOYER";
export const LOGIN_EMPLOYER_SUCCESS = "LOGIN_EMPLOYER_SUCCESS";
export const LOGIN_EMPLOYER_FAIL = "LOGIN_EMPLOYER_FAIL";

export const LOGIN_EMPLOYEE = "LOGIN_EMPLOYEE";
export const LOGIN_EMPLOYEE_SUCCESS = "LOGIN_EMPLOYEE_SUCCESS";
export const LOGIN_EMPLOYEE_FAIL = "LOGIN_EMPLOYEE_FAIL";

export const LOGIN_ADMIN = "LOGIN_ADMIN";
export const LOGIN_ADMIN_SUCCESS = "LOGIN_ADMIN_SUCCESS";
export const LOGIN_ADMIN_FAIL = "LOGIN_ADMIN_FAIL";

export const GET_PROFILE_ADMIN = "GET_PROFILE_ADMIN";
export const GET_PROFILE_ADMIN_SUCCESS = "GET_PROFILE_ADMIN_SUCCESS";
export const GET_PROFILE_ADMIN_FAIL = "GET_PROFILE_ADMIN_FAIL";

export const GET_PROFILE_EMPLOYEE = "GET_PROFILE_EMPLOYEE";
export const GET_PROFILE_EMPLOYEE_SUCCESS = "GET_PROFILE_EMPLOYEE_SUCCESS";
export const GET_PROFILE_EMPLOYEE_FAIL = "GET_PROFILE_EMPLOYEE_FAIL";

export const GET_PROFILE_EMPLOYER = "GET_PROFILE_EMPLOYER";
export const GET_PROFILE_EMPLOYER_SUCCESS = "GET_PROFILE_EMPLOYER_SUCCESS";
export const GET_PROFILE_EMPLOYER_FAIL = "GET_PROFILE_EMPLOYER_FAIL";

export const GET_OFFERS = "GET_OFFERS";
export const GET_OFFERS_SUCCESS = "GET_OFFERS_SUCCESS";
export const GET_OFFERS_FAIL = "GET_OFFERS_FAIL";

export const UPDATE_PROFILE_EMPLOYEE = "UPDATE_PROFILE_EMPLOYEE";

export const CREATE_JOB = "CREATE_JOB";
export const CREATE_JOB_SUCCESS = "CREATE_JOB_SUCCESS";
export const CREATE_JOB_FAIL = "CREATE_JOB_FAIL";

export const UPDATE_PROFILE_EMPLOYER = "UPDATE_PROFILE_EMPLOYEE";
export const UPDATE_PROFILE_EMPLOYER_SUCC = "UPDATE_PROFILE_EMPLOYER_SUCC";
export const UPDATE_PROFILE_EMPLOYER_FAIL = "UPDATE_PROFILE_EMPLOYER_FAIL";

export const DELETE_JOB = "DELETE_JOB";
export const DELETE_JOB_SUCCESS = "DELETE_JOB_SUCCESS";
export const DELETE_JOB_FAIL = "DELETE_JOB_FAIL";

export const UPDATE_JOB = "UPDATE_JOB";
export const UPDATE_JOB_SUCCESS = "UPDATE_JOB_SUCCESS";
export const UPDATE_JOB_FAIL = "UPDATE_JOB_FAIL";

export const GET_ONE_OFFER = "GET_ONE_OFFER";
export const GET_ONE_OFFER_SUCCESS = "GET_ONE_OFFER_SUCCESS";
export const GET_ONE_OFFER_FAIL = "GET_ONE_OFFER_FAIL";

export const GET_USERS = "GET_USERS";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAIL = "GET_USERS_FAIL";

export const DELETE_USER = "Delete_USER";
export const DELETE_USER_SUCCESS = "Delete_USER_SUCCESS";
export const DELETE_USER_FAIL = "Delete_USER_FAIL";

export const GET_COMPANIES = "GET_COMPANIES";
export const GET_COMPANIES_SUCCESS = "GET_COMPANIES_SUCCESS";
export const GET_COMPANIES_FAIL = "GET_COMPANIES_FAIL";

export const DELETE_COMPANY = "Delete_COMPANY";
export const DELETE_COMPANY_SUCCESS = "Delete_COMPANY_SUCCESS";
export const DELETE_COMPANY_FAIL = "Delete_COMPANY_FAIL";
